<a href="https://colab.research.google.com/github/jcarvajalri/MineriaDatosUN/blob/main/Taller_1_MD_2021_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Universidad Nacional de Colombia
##Minería de Datos

## Prof. Elizabeth León
## **Ejercicio Tipos de datos**


##Presentado por: John David Carvajal


---



**Carga de archivos**

1. Bajar el archivo Iris del repositorio UCI de Machine Learning UCI(1936):  https://archive.ics.uci.edu/ml/index.php

2. Cambiarle el nombre por iris.csv
3. Editarlo y colocar en la primera fila:
sepalo_largo,sepalo_ancho,petalo_largo,petal_ancho,clase

In [ ]:
import pandas as pd
import io

In [ ]:
import seaborn as sns
df = sns.load_dataset('iris')
df.head()
df.shape
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Para visualizar el contenido del archivo:

**Responder** 

¿Qué tipo de datos contiene este conjunto de datos? 

*R//:* Contiene la caracteristicas de tipos de especie de flores (setosa, versicolor, virginica) como , largo y ancho del cepalo  y del petalo. 


¿Que características tienen cada una de sus dimensiones?

*R//:* A continuación se presenta las caracteristicas de cada una de las dimensiones: 



*   sepal length: Atributo numerico en cm. Dato continuo
*   sepal width: Atributo numérico en cm. Dato continuo
*   petal length: Atributo numérico en cm. Dato continuo
*   petal width: Atributo numérico en cm, Dato continuo
*   species: Atributo string o varchar , contiene la descripción de la clase de flor: setosa, versicolor, virginica.



¿Qué tarea de minería podría realizarse con este conjunto?

*R//:* Con este conjunto de datos se podria realizar una correlación entre las variables, analizar la variabilidad de los atributos númericos , una clasificación y comparación entre los componenest.

¿Qué puede decir de la calidad del conjunto de datos?

*R//:* La calidad de los datos es buena , sin embargo considero que es muy escaza. Adicionalmente se podría tener otros atributos para cada registro como color. No se identifica que algún atributo este fuera del rango frente a los otros. Tampoco se identifica datos repetidos.

**2. Cargar el archivo canasto.csv**

In [ ]:
uploaded = files.upload()
df2 = pd.read_csv(io.BytesIO(uploaded['canasto.txt']), sep=';')
df2.shape
df2

Saving canasto.txt to canasto.txt

   ID  Leche  Cerveza  Panales    Pan  Mantequilla  Galletas
0   1   True     True     True  False        False     False
1   2   True    False    False   True         True     False
2   3   True    False     True  False        False      True
3   4  False    False    False   True         True      True
4   5  False     True     True  False        False      True
5   6   True    False     True   True         True     False
6   7  False    False     True   True         True     False
7   8  False     True     True  False        False     False
8   9   True    False     True   True         True     False
9  10  False     True    False  False        False      True

**Responder**

¿Qué tipo de datos contiene este conjunto de datos?

*R//:* El set de datos contieene la relación de articulos que compra una persona cuando hace mercado. Esta relación hace referencia a los articulos que compro un cliente (cada registro) en una compra.Por ejemplo en la fila 1, el cliente llevo leche, cerveza y pañales. 

¿Que características tienen cada una de sus dimensiones?

*R//:* A continuación se presenta las caracteristicas de cada uno de los atributos 

*   Leche: Atributo Booleano (True o False)
*   Cerveza: Atributo Booleano (True o False)
*   Pañales: Atributo Booleano (True o False)
*   Pan: Atributo Booleano (True o False)
*   Mantequilla: Atributo Booleano (True o False)
*   Galletas: Atributo Booleano (True o False)

Cada registro hace referencia a la compra que realizó un cliente y los articulos que llevo.

¿Qué tarea de minería podría realizarse con este conjunto?

*R//:* Con este conjunto de datos se podria realizar una correlación entre las variables, es decir que articulos estan relacionados en una misma compra. Tambien se puede determinar cual es el articulo que mas se vende, o tiene por lo general una dependencia de otro.

¿Qué puede decir de la calidad del conjunto de datos?

*R//:* La calidad de los datos es buena, todos los atributos mantienen el mismo estandar de los booleanos, sin embargo considero que es muy escaza para realizar un análisis mas profunco. Adicionalmente se podría tener otros atributos para cada registro como como la hora en que se realiza la compra de los articulos , y la cantidad de cada articulo.

**3. Ejercicio**
Obtenga el conjunto Adult del repositorio UCI Machine Learning Repository (https://archive.ics.uci.edu/ml/index.php). Este conjunto de datos corresponde a datos del censo de USA de 1994

1. Cárguelo

*R//* El set de datos que se selecciono fueron accidentes de carros. A continuación se encuentra la carga de datos.

In [ ]:
uploaded = files.upload()
df3 = pd.read_csv(io.BytesIO(uploaded['car_crashes.csv']), sep=',')
df3.shape
df3

Saving car_crashes.csv to car_crashes.csv

    total  speeding  alcohol  ...  ins_premium  ins_losses  abbrev
0    18.8     7.332    5.640  ...       784.55      145.08      AL
1    18.1     7.421    4.525  ...      1053.48      133.93      AK
2    18.6     6.510    5.208  ...       899.47      110.35      AZ
3    22.4     4.032    5.824  ...       827.34      142.39      AR
4    12.0     4.200    3.360  ...       878.41      165.63      CA
5    13.6     5.032    3.808  ...       835.50      139.91      CO
6    10.8     4.968    3.888  ...      1068.73      167.02      CT
7    16.2     6.156    4.860  ...      1137.87      151.48      DE
8     5.9     2.006    1.593  ...      1273.89      136.05      DC
9    17.9     3.759    5.191  ...      1160.13      144.18      FL
10   15.6     2.964    3.900  ...       913.15      142.80      GA
11   17.5     9.450    7.175  ...       861.18      120.92      HI
12   15.3     5.508    4.437  ...       641.96       82.75      ID
13   12.8     4.608    4.352  ...       803.11      139.15      IL
14   14.5     3.625    4.205  ...       710.46      108.92      IN
15   15.7     2.669    3.925  ...       649.06      114.47      IA
16   17.8     4.806    4.272  ...       780.45      133.80      KS
17   21.4     4.066    4.922  ...       872.51      137.13      KY
18   20.5     7.175    6.765  ...      1281.55      194.78      LA
19   15.1     5.738    4.530  ...       661.88       96.57      ME
20   12.5     4.250    4.000  ...      1048.78      192.70      MD
21    8.2     1.886    2.870  ...      1011.14      135.63      MA
22   14.1     3.384    3.948  ...      1110.61      152.26      MI
23    9.6     2.208    2.784  ...       777.18      133.35      MN
24   17.6     2.640    5.456  ...       896.07      155.77      MS
25   16.1     6.923    5.474  ...       790.32      144.45      MO
26   21.4     8.346    9.416  ...       816.21       85.15      MT
27   14.9     1.937    5.215  ...       732.28      114.82      NE
28   14.7     5.439    4.704  ...      1029.87      138.71      NV
29   11.6     4.060    3.480  ...       746.54      120.21      NH
30   11.2     1.792    3.136  ...      1301.52      159.85      NJ
31   18.4     3.496    4.968  ...       869.85      120.75      NM
32   12.3     3.936    3.567  ...      1234.31      150.01      NY
33   16.8     6.552    5.208  ...       708.24      127.82      NC
34   23.9     5.497   10.038  ...       688.75      109.72      ND
35   14.1     3.948    4.794  ...       697.73      133.52      OH
36   19.9     6.368    5.771  ...       881.51      178.86      OK
37   12.8     4.224    3.328  ...       804.71      104.61      OR
38   18.2     9.100    5.642  ...       905.99      153.86      PA
39   11.1     3.774    4.218  ...      1148.99      148.58      RI
40   23.9     9.082    9.799  ...       858.97      116.29      SC
41   19.4     6.014    6.402  ...       669.31       96.87      SD
42   19.5     4.095    5.655  ...       767.91      155.57      TN
43   19.4     7.760    7.372  ...      1004.75      156.83      TX
44   11.3     4.859    1.808  ...       809.38      109.48      UT
45   13.6     4.080    4.080  ...       716.20      109.61      VT
46   12.7     2.413    3.429  ...       768.95      153.72      VA
47   10.6     4.452    3.498  ...       890.03      111.62      WA
48   23.8     8.092    6.664  ...       992.61      152.56      WV
49   13.8     4.968    4.554  ...       670.31      106.62      WI
50   17.4     7.308    5.568  ...       791.14      122.04      WY

[51 rows x 8 columns]

2. Describa el conjunto de datos: Número de instancias,Número de atributos. ¿Qué tareas de la minería de datos se pueden aplicar? Explique.

*R//:* El conjunto de datos seleccionado hace referencia a accidentes de carros. Cada variable atributo hace refrencia a al accediente. aidcionalmente hay un atributo que habla del total de accidentes que tienen tuvieron las mismas caracteristicas dentro de una ciudad..  Adicionalmente se encuentra una relación con con los respectivos seguros de los carros.

Se puede reralizar una tarea de mineria de correlaccion de datos entre los siniestros de diferentes ciudades , teniendo en cuenta atributos como el grado de alcohol del conductos. Tambien se puede realizar un trabajo de clasifiación.

3. ¿El conjunto de datos está etiquetado? ¿Cuántas clases tiene el conjunto de datos?

*R//:* Lo datos se encuentran etiqeutados, a continuación se encuentran los atributos que tiene el set de datos: 


*   Total : Atributo númerico. Describe la cantidad de accidentes con los atributos posteriores.
*   Speeding: Atributo numérico, velocidad del vehiculo cuando tuvo el accidente.
*   Alcohol: Atributo numnérico. Grado del alcohol del conductor.
*   No_Distracted. Atributo numérico . Indicador de distracción del conductor.
*  No_Previus: Atributo numerico.
*   Ins_Premiums: Atributo Numérico. Seguro premium del vehículo.
*  Ins_Losses: Perdida del seguro.
*  Abbrev. Atributo describtivo, Indicador de la ciudad donde se presentaron los siniestros. 




4. ¿Cuántos atributos son numéricos y cuántos categóricos? De los atributos numéricos ¿Cuántos son continuos y cuántos discretos?

*R//* 7 Atributos son numericos , y 1 atributo es categorico.Los 7 atributos numericos son continuos. El tributo categorico se podría definir como discreto ya que hace refrencia a una ciudad, la cual la podríamos determinar con un cod. 

5. ¿Existen atributos binarios, ordinales, intervalo o de radio? ¿cuáles?

*R//* El set de datos no presneta atributos binarios , cada uno de los datos numericos se encuentran dentro de un intervalo , y no se evidencian datos fuera de rando. El dato que hace ref a abre es descriptivo y representa la ciudad donde paso el siniestro.